### ISSUE TITLE
Allow optional custom subpath for resource requests in config.js

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-admin#12]
Depending on how a developer's nginx environment is set up, it may be necessary to configure a custom subpath for resource (js, css) requests.  This could be an optional parameter in config.js, and default to an empty string when not included in config.js.

**Comment by iremaka** [comment]
Resolution in [+3 Ar 3-21-2018 Optional admin prefix Variable Supported](https://github.com/Greenstand/treetracker-admin/pull/13)
