### ISSUE TITLE
Species: Only query capture count if user has permission to manage species

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin#607]
We currently augment every species list query with the capture counts for each species:
https://github.com/Greenstand/treetracker-admin-api/blob/a400e8f2fa894de5d1bc11dec545e2e37037d578/src/controllers/species.controller.ts#L68

This is much more efficient than having the client query for each species individually, but adds several seconds onto the initial query.

Currently, the Species tool is only available to users with the `super_permission` policy in their roles (although soon that will include those with `manage_species`), which is the only place the counts are displayed in the client.

Therefore, there's no need to include these counts when the user doesn't have one of those policies.
That would significantly reduce the loading time for Organization users in particular.

**Comment by kothariroshni8** [comment]
I would like to work on this issue

**Comment by kothariroshni8** [comment]
I would like to confirm my understanding.
1. first we need to check whether user has role i.e "Species Manager" or "admin"
2. if yes then we will calculate the capture count for each species
3. if no then we will not calculate it and simply return the species.

**Comment by nmcharlton** [comment]
@kothariroshni8 That's correct.
