### ISSUE TITLE
Payment page: The filter function Bug

### ISSUE THREAD

**Issue by Tarek-Bohdima** [Greenstand/treetracker-admin#629]
Payment page: The filter function :
- filter defaults to paid only
- filter by Payment status shows paid only.
- filter by Grower name or phone doesn’t work
- filter by both payment status and grower name doesn’t work

**Comment by dadiorchen** [comment]
> Payment page: The filter function :
> 
> * filter defaults to paid only
@Tarek-Bohdima That's the expected behavior, in the payment page, we show `paid` records
> * filter by Payment status shows paid only.
@Tarek-Bohdima what do you mean by that?
> * filter by Grower name or phone doesn’t work
> * filter by both payment status and grower name doesn’t work
@Tarek-Bohdima I can not reproduce this, can you explain or give a screenshot or so?

**Comment by Tarek-Bohdima** [comment]
@dadiorchen I mean if you filter Payment by ALL it shows only paid , not calculated and paid as it should be ( from what i presume)

other 2 issues:
First 1 : I assumed the default to be all 
last issue : steps to reproduce:
choose filter by organization: pick any
apply
no data to display
Press filter again -> RESET
no data to display
Filter again by payment status ALL or Calculated or Paid
no data to display

no way to show data again unless you refresh the page

**Comment by dadiorchen** [comment]
Thanks @Tarek-Bohdima I confirmed the second issue: Greenstand/treetracker-admin-client#608

**Comment by dadiorchen** [comment]
So now this is a duplicated issue, just leave the https://github.com/Greenstand/treetracker-admin-client/issues/608 open, I'll close this one now
