### ISSUE TITLE
Adding Species to the list does not work

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin#650]
I did not manage to add tree species to the legacy DB.

**Comment by nmcharlton** [comment]
The legacy `/species` endpoint requires a UUID for new species – the API should be responsible for creating UUIDs.

**Comment by neil-gok** [comment]
@sebastiangaertner I tested this in Dev, and it appears to be creating the species record as expected.  Can this be closed?

**Comment by sebastiangaertner** [comment]
Yes can be closed. Must have fallen through the cracks. Thank you!
